apiVersion: schemas.schemahero.io/v1alpha4
kind: Table
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: user-cluster
spec:
  database: kotsadm-postgres
  name: user_cluster
  requires: []
  schema:
    postgres:
      primaryKey: []
      columns:
      - name: user_id
        type: text
        constraints:
          notNull: true
      - name: cluster_id
        type: text
        constraints:
          notNull: true
